/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzaria.view;

import pizzaria.controller.ClienteController;

/**
 *
 * @author tomat
 */
public class ClienteButtonControl extends javax.swing.JPanel {

    /**
     * Creates new form BotoesControleCentral
     */
    public ClienteButtonControl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_cliente_listar = new javax.swing.JButton();

        btn_cliente_listar.setText("Listar Todos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(btn_cliente_listar, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btn_cliente_listar)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cliente_listar;

    // End of variables declaration//GEN-END:variables
    public void setController(ClienteController controller) {

//        this.btn_cliente_novo.addActionListener(e -> controller.criarCliente());
//        this.btn_cliente_atualizar.addActionListener(e -> controller.atualizarCliente());
//        this.btn_cliente_excluir.addActionListener(e -> controller.excluirCliente());
        this.btn_cliente_listar.addActionListener(e -> controller.listarCliente());
    }

}
