/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzaria.gui;

import java.awt.Component;
import java.util.ArrayList;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JFrame;
import javax.swing.JList;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;
import pizzaria.model.Circulo;
import pizzaria.model.Cliente;
import pizzaria.model.Forma;
import pizzaria.model.Pedido;
import pizzaria.model.Pizza;
import pizzaria.model.Quadrado;
import pizzaria.model.SaborPizza;
import pizzaria.model.Triangulo;
import pizzaria.utils.FormaPizzaEnum;
import pizzaria.utils.TiposPizza;

/**
 *
 * @author leo_o
 */
public class TelaNovoPedido extends javax.swing.JFrame {

    ArrayList<Pizza> listaPizzas;
    Pedido clientePedido;
    Cliente clienteSelecionado;
    String modo;

    public TelaNovoPedido(Cliente cliente) {

        clienteSelecionado = cliente;
        clientePedido = cliente.getPedido();
        listaPizzas = new ArrayList();

        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        btn_pedido_excluir.setEnabled(false);

        for (int i = 0; i < TiposPizza.pizzaSimples.getListaSabores().size(); i++) {
            cbx_pedido_sabor1.addItem(TiposPizza.pizzaSimples.getListaSabores().get(i));
            cbx_pedido_sabor2.addItem(TiposPizza.pizzaSimples.getListaSabores().get(i));
        }
        for (int i = 0; i < TiposPizza.pizzaEspecial.getListaSabores().size(); i++) {
            cbx_pedido_sabor1.addItem(TiposPizza.pizzaEspecial.getListaSabores().get(i));
            cbx_pedido_sabor2.addItem(TiposPizza.pizzaEspecial.getListaSabores().get(i));
        }
        for (int i = 0; i < TiposPizza.pizzaPremium.getListaSabores().size(); i++) {
            cbx_pedido_sabor1.addItem(TiposPizza.pizzaPremium.getListaSabores().get(i));
            cbx_pedido_sabor2.addItem(TiposPizza.pizzaPremium.getListaSabores().get(i));
        }

        cbx_pedido_sabor1.setRenderer(new MyObjectListCellRenderer());
        cbx_pedido_sabor2.setRenderer(new MyObjectListCellRenderer());

        if (clientePedido != null) {
            listaPizzas.addAll(clientePedido.getListaPizzas());
            loadTablePizzas();
            label_preco_total.setText(String.valueOf(clientePedido.getPreco()));
        }
    }

    private TelaNovoPedido() {
    }

    public void loadTablePizzas() {
        Object colunas[] = {"Sabor 1", "Sabor 2", "Forma", "Área", "Lado ou Raio", "Preço"};
        DefaultTableModel modelo = new DefaultTableModel(colunas, 0);

        for (int i = 0; i < listaPizzas.size(); i++) {
            Object dados[] = new Object[]{
                listaPizzas.get(i).getSabor1().getNome(),
                listaPizzas.get(i).getSabor2().getNome(),
                listaPizzas.get(i).getForma().getNomeForma(),
                listaPizzas.get(i).getArea(),
                listaPizzas.get(i).getLadoOuRaio(),
                listaPizzas.get(i).getPrecoTotal(),};
            modelo.addRow(dados);
        }
        tb_pizzas.setModel(modelo);
        tb_pizzas.setDefaultEditor(Object.class, null);

        tb_pizzas.getColumnModel().getColumn(0).setPreferredWidth(100);
        tb_pizzas.getColumnModel().getColumn(1).setPreferredWidth(150);
        tb_pizzas.getColumnModel().getColumn(2).setPreferredWidth(100);
        tb_pizzas.getColumnModel().getColumn(3).setPreferredWidth(100);
        tb_pizzas.getColumnModel().getColumn(4).setPreferredWidth(100);
        tb_pizzas.getColumnModel().getColumn(5).setPreferredWidth(100);

    }

    public class MyObjectListCellRenderer extends DefaultListCellRenderer {

        public Component getListCellRendererComponent(
                JList list,
                Object value,
                int index,
                boolean isSelected,
                boolean cellHasFocus) {
            if (value instanceof SaborPizza) {
                value = ((SaborPizza) value).getNome() + " - " + ((SaborPizza) value).getTipo().getNome();
            }
            super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            return this;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        cbx_pedido_sabor1 = new javax.swing.JComboBox<>();
        cbx_pedido_sabor2 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        r_pedido_quadrado = new javax.swing.JRadioButton();
        r_pedido_triangulo = new javax.swing.JRadioButton();
        r_pedido_circulo = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        r_pedido_cm = new javax.swing.JRadioButton();
        r_pedido_cm_quadrados = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        c_pedido_tamanho = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_pizzas = new javax.swing.JTable();
        btn_pedido_excluir = new javax.swing.JButton();
        btn_pedido_salvar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        label_preco_total = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Novo Pedido"));

        cbx_pedido_sabor1.setToolTipText("Sabor 2");
        cbx_pedido_sabor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_pedido_sabor1ActionPerformed(evt);
            }
        });

        cbx_pedido_sabor2.setToolTipText("Sabor 1");
        cbx_pedido_sabor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_pedido_sabor2ActionPerformed(evt);
            }
        });

        jLabel14.setText("Forma:");

        buttonGroup1.add(r_pedido_quadrado);
        r_pedido_quadrado.setText("Quadrado");
        r_pedido_quadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_pedido_quadradoActionPerformed(evt);
            }
        });

        buttonGroup1.add(r_pedido_triangulo);
        r_pedido_triangulo.setText("Triângulo");

        buttonGroup1.add(r_pedido_circulo);
        r_pedido_circulo.setText("Círculo");

        jLabel1.setText("Tamanho:");

        buttonGroup2.add(r_pedido_cm);
        r_pedido_cm.setText("Lado ou raio em cm");
        r_pedido_cm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_pedido_cmActionPerformed(evt);
            }
        });

        buttonGroup2.add(r_pedido_cm_quadrados);
        r_pedido_cm_quadrados.setText("Área em cm²");
        r_pedido_cm_quadrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_pedido_cm_quadradosActionPerformed(evt);
            }
        });

        jLabel2.setText("Sabor 1");

        jLabel3.setText("Sabor 2");

        c_pedido_tamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_pedido_tamanhoActionPerformed(evt);
            }
        });

        tb_pizzas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sabor 1", "Sabor 2", "Forma", "Área", "Lado ou Raio", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_pizzas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_pizzasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_pizzas);

        btn_pedido_excluir.setText("Excluir");
        btn_pedido_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pedido_excluirActionPerformed(evt);
            }
        });

        btn_pedido_salvar.setText("Salvar");
        btn_pedido_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pedido_salvarActionPerformed(evt);
            }
        });

        jLabel4.setText("Preço Total: R$");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(r_pedido_triangulo)
                                    .addComponent(r_pedido_quadrado)
                                    .addComponent(r_pedido_circulo)))
                            .addComponent(cbx_pedido_sabor1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_preco_total)))
                        .addGap(18, 29, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbx_pedido_sabor2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(c_pedido_tamanho))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(r_pedido_cm)
                                        .addGap(18, 18, 18)
                                        .addComponent(r_pedido_cm_quadrados))))
                            .addComponent(btn_pedido_salvar, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_pedido_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_pedido_excluir)
                    .addComponent(jLabel4)
                    .addComponent(label_preco_total))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbx_pedido_sabor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_pedido_sabor2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(r_pedido_quadrado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(r_pedido_triangulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(r_pedido_circulo))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(c_pedido_tamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r_pedido_cm)
                            .addComponent(r_pedido_cm_quadrados))
                        .addGap(28, 28, 28)
                        .addComponent(btn_pedido_salvar)))
                .addGap(153, 153, 153))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 525, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r_pedido_quadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_pedido_quadradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_pedido_quadradoActionPerformed

    private void r_pedido_cmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_pedido_cmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_pedido_cmActionPerformed

    private void r_pedido_cm_quadradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_pedido_cm_quadradosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_pedido_cm_quadradosActionPerformed

    private void cbx_pedido_sabor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_pedido_sabor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_pedido_sabor2ActionPerformed

    private void c_pedido_tamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_pedido_tamanhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_pedido_tamanhoActionPerformed

    private void btn_pedido_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pedido_salvarActionPerformed

        Forma forma;
        boolean isMetricaCmQuadrado;
        SaborPizza sabor1 = (SaborPizza) cbx_pedido_sabor1.getSelectedItem();
        SaborPizza sabor2 = (SaborPizza) cbx_pedido_sabor2.getSelectedItem();

        if (sabor1 == null || sabor2 == null) {
            showMessageDialog(null, "Defina os sabores da pizza!");
            return;
        }

        if (r_pedido_circulo.isSelected()) {
            forma = new Circulo();
        } else if (r_pedido_quadrado.isSelected()) {
            forma = new Quadrado();
        } else if (r_pedido_triangulo.isSelected()) {
            forma = new Triangulo();
        } else {
            showMessageDialog(null, "Defina o formato da pizza!");
            return;
        }

        if (r_pedido_cm.isSelected()) {
            isMetricaCmQuadrado = false;
        } else if (r_pedido_cm_quadrados.isSelected()) {
            isMetricaCmQuadrado = true;
        } else {
            showMessageDialog(null, "Defina a metrica a ser utilizada!");
            return;
        }

        double precoSabor1 = sabor1.getTipo().getPrecoCmQuadrado();
        double precoSabor2 = sabor2.getTipo().getPrecoCmQuadrado();
        if (precoSabor1 == 0 || precoSabor2 == 0) {
            showMessageDialog(null, "Defina o preço do tipo das pizzas selecionadas!");
            return;
        }

        double tamanhoInformado;
        try {
            tamanhoInformado = Double.parseDouble(c_pedido_tamanho.getText());
        } catch (Exception e) {
            showMessageDialog(null, "Valor do campo tamanho inválido!");
            return;
        }

        double precoPizza;
        double ladoOuRaio;
        double areaTotal;

        if (isMetricaCmQuadrado) {
            areaTotal = tamanhoInformado;
            ladoOuRaio = forma.calcularLadoOuRaio(areaTotal);
        } else {
            ladoOuRaio = tamanhoInformado;
            areaTotal = forma.calcularArea(ladoOuRaio);
        }

        if (forma.getForma() == FormaPizzaEnum.QUADRADO && (ladoOuRaio < 10 || ladoOuRaio > 40) && !isMetricaCmQuadrado) {
            showMessageDialog(null, "O tamanho do lado para pizzas quadradas é de no mínimo 10cm e no máximo 40cm");
            return;
        } else if (forma.getForma() == FormaPizzaEnum.TRIANGULO && (ladoOuRaio < 20 || ladoOuRaio > 60) && !isMetricaCmQuadrado) {
            showMessageDialog(null, "O tamanho do lado para pizzas triangulares é de no mínimo 20cm e no máximo 60cm");
            return;
        } else if (forma.getForma() == FormaPizzaEnum.CIRCULO && (ladoOuRaio < 7 || ladoOuRaio > 23) && !isMetricaCmQuadrado) {
            showMessageDialog(null, "O tamanho do raio para pizzas circulares é de no mínimo 10cm e no máximo 23cm");
            return;
        } else if (isMetricaCmQuadrado && (areaTotal < 100 || areaTotal > 1600)) {
            showMessageDialog(null, "O tamanho da área da pizza deve ser de no mínimo 100cm2 e de no máximo 1600cm2");
            return;
        }

        precoPizza = ((areaTotal * precoSabor1) + (areaTotal * precoSabor2)) / 2;

        if (clientePedido == null) {
            clientePedido = new Pedido(clienteSelecionado);
            clienteSelecionado.setPedido(clientePedido);
        }

        Pizza novaPizza = new Pizza(clientePedido, forma, isMetricaCmQuadrado, areaTotal, ladoOuRaio, sabor1, sabor2, precoPizza);
        listaPizzas.add(novaPizza);
        clientePedido.addPizza(novaPizza);
        clientePedido.setPreco(clientePedido.getPreco() + precoPizza);
        label_preco_total.setText(String.valueOf(clientePedido.getPreco()));
        loadTablePizzas();
    }//GEN-LAST:event_btn_pedido_salvarActionPerformed

    private void cbx_pedido_sabor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_pedido_sabor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_pedido_sabor1ActionPerformed

    private void btn_pedido_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pedido_excluirActionPerformed
        int index = tb_pizzas.getSelectedRow();
        if (index >= 0 && index < listaPizzas.size()) {
            Pizza pizzaParaExcluir = listaPizzas.get(index);
            clientePedido.setPreco(clientePedido.getPreco() - pizzaParaExcluir.getPrecoTotal());
            label_preco_total.setText(String.valueOf(clientePedido.getPreco()));
            listaPizzas.remove(index);
            clientePedido.removePizza(index);
        }
        loadTablePizzas();
        btn_pedido_excluir.setEnabled(false);
    }//GEN-LAST:event_btn_pedido_excluirActionPerformed

    private void tb_pizzasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_pizzasMouseClicked
        int index = tb_pizzas.getSelectedRow();
        if (index >= 0 && index < listaPizzas.size()) {
            btn_pedido_excluir.setEnabled(true);
        }
    }//GEN-LAST:event_tb_pizzasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaNovoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaNovoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaNovoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNovoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaNovoPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_pedido_excluir;
    private javax.swing.JButton btn_pedido_salvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField c_pedido_tamanho;
    private javax.swing.JComboBox<SaborPizza> cbx_pedido_sabor1;
    private javax.swing.JComboBox<SaborPizza> cbx_pedido_sabor2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_preco_total;
    private javax.swing.JRadioButton r_pedido_circulo;
    private javax.swing.JRadioButton r_pedido_cm;
    private javax.swing.JRadioButton r_pedido_cm_quadrados;
    private javax.swing.JRadioButton r_pedido_quadrado;
    private javax.swing.JRadioButton r_pedido_triangulo;
    private javax.swing.JTable tb_pizzas;
    // End of variables declaration//GEN-END:variables
}
